/*
 * lutgen_ym2151 - emit the YM2151's lookup tables as flash-resident constants.
 *
 *   lutgen_ym2151 <out.h>            write the header
 *   lutgen_ym2151 <out.h> --check    fail if the committed header differs
 *
 * WHY. The seven tables are ~70 KB of .bss, and an RP2350 running the OutRun
 * engine does not have it (see port/README.md). They are pure functions of the
 * chip clock and the sample rate, both fixed at build time, so they belong in
 * flash.
 *
 * HOW, AND WHY IT IS TRUSTWORTHY. This does not reimplement the tables. It
 * links the real cannonball/src/main/hwaudio/ym2151.cpp, calls the constructor
 * and init() the way OSoundInt does, and dumps what that code produced. The
 * generated header is therefore correct by construction rather than by careful
 * transcription - the same discipline as hosttest/verify_decode.
 *
 * The --check mode is what keeps it honest over time: run it after touching the
 * vendored engine and it fails loudly if the committed tables no longer match.
 */

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "frontend/config.hpp"
#include "hwaudio/ym2151.hpp"

// OSoundInt::SOUND_CLOCK - engine/audio/osoundint.hpp
static const uint32_t SOUND_CLOCK = 4000000;

// Globals the engine expects. config comes from port/config.cpp.
extern uint32_t freq[11 * 768];
extern int32_t dt1_freq[8 * 32];
extern uint32_t noise_tab[32];
extern uint32_t tim_A_tab[1024];
extern uint32_t tim_B_tab[256];

// Hooks compiled into ym2151.cpp under OUTRUN_LUTGEN.
extern const signed int *outrun_ym2151_tl_tab(void);
extern const unsigned int *outrun_ym2151_sin_tab(void);
extern int outrun_ym2151_tl_tab_len(void);
extern int outrun_ym2151_sin_tab_len(void);

static std::string out;

static void emit(const char *type, const char *name, const void *data, int len, bool is_signed)
{
    char buf[64];
    snprintf(buf, sizeof(buf), "static const %s %s[%d] = {\n", type, name, len);
    out += buf;
    for (int i = 0; i < len; i++)
    {
        if (is_signed)
        {
            snprintf(buf, sizeof(buf), "%d,", ((const int32_t *)data)[i]);
        }
        else
        {
            snprintf(buf, sizeof(buf), "%uu,", ((const uint32_t *)data)[i]);
        }
        out += buf;
        out += ((i % 12) == 11 || i == len - 1) ? "\n" : " ";
    }
    out += "};\n\n";
}

int main(int argc, char **argv)
{
    if (argc < 2)
    {
        fprintf(stderr, "usage: lutgen_ym2151 <out.h> [--check]\n");
        return 2;
    }
    const char *path = argv[1];
    bool check = (argc > 2 && !strcmp(argv[2], "--check"));

    // Exactly what OSoundInt::init() does.
    YM2151 ym(0.5f, SOUND_CLOCK);
    ym.init(config.sound.rate, config.fps);

    out = "/*\n"
          " * GENERATED by hosttest/lutgen_ym2151 - DO NOT EDIT.\n"
          " *\n"
          " * The YM2151's lookup tables, baked into flash so they cost no RAM.\n"
          " * Produced by running cannonball/src/main/hwaudio/ym2151.cpp's own\n"
          " * init_tables() / init_chip_tables() on the host, for a 4 MHz chip clock\n"
          " * at 44100 Hz. Regenerate and verify with:\n"
          " *     ./hosttest/build.sh lutgen\n"
          " *     ./hosttest/build.sh check\n"
          " */\n\n"
          "#pragma once\n\n#include <stdint.h>\n\n";

    emit("uint32_t", "ym2151_lut_freq", freq, 11 * 768, false);
    emit("int32_t", "ym2151_lut_dt1_freq", dt1_freq, 8 * 32, true);
    emit("uint32_t", "ym2151_lut_noise_tab", noise_tab, 32, false);
    emit("uint32_t", "ym2151_lut_tim_A_tab", tim_A_tab, 1024, false);
    emit("uint32_t", "ym2151_lut_tim_B_tab", tim_B_tab, 256, false);
    emit("int32_t", "ym2151_lut_tl_tab", outrun_ym2151_tl_tab(), outrun_ym2151_tl_tab_len(), true);
    emit("uint32_t", "ym2151_lut_sin_tab", outrun_ym2151_sin_tab(), outrun_ym2151_sin_tab_len(),
         false);

    if (check)
    {
        FILE *f = fopen(path, "rb");
        if (!f)
        {
            fprintf(stderr, "%s does not exist - run ./hosttest/build.sh lutgen\n", path);
            return 1;
        }
        std::string have;
        char buf[4096];
        size_t n;
        while ((n = fread(buf, 1, sizeof(buf), f)) > 0)
        {
            have.append(buf, n);
        }
        fclose(f);
        if (have != out)
        {
            fprintf(stderr,
                    "MISMATCH: %s differs from what the vendored ym2151.cpp now produces\n"
                    "  (committed %zu bytes, generated %zu). Regenerate it.\n",
                    path, have.size(), out.size());
            return 1;
        }
        printf("%s matches the vendored ym2151.cpp.\n", path);
        return 0;
    }

    FILE *f = fopen(path, "wb");
    if (!f)
    {
        fprintf(stderr, "cannot write %s\n", path);
        return 1;
    }
    fwrite(out.data(), 1, out.size(), f);
    fclose(f);

    long bytes = (11 * 768 + 8 * 32 + 32 + 1024 + 256 + outrun_ym2151_tl_tab_len() +
                  outrun_ym2151_sin_tab_len()) *
                 4L;
    printf("Wrote %s (%zu bytes of source, %ld bytes of tables moved to flash)\n", path, out.size(),
           bytes);
    return 0;
}
